name: dart_fundamentos
description: Projeto referente ao curso de dart fundamento da academia flutter
version: 1.0.0
homepage: http://academiadoflutter.com.br

environment:
  sdk: ^3.0.6

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
